name: Steven Caldicott Wilson
favicon: null
layout_spectrum: 0.7491548371035606
typography_spectrum: 0.34503636392764747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9738367120735347
  lightness: 0.913286377908662
  saturation: 0.7155655473470688
  rhythmicContrast: 0.6992182373069227
purpose: []
