name: Steven Caldicott Wilson
favicon: null
layout_spectrum: 0.7491548371035606
typography_spectrum: 0.34503636392764747
title: oratorio tenor / voice coach / cocktail and cabaret pianist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090b0c'
    - '#a6bfc5'
    - '#617e86'
    - '#003f62'
    - '#584c40'
  brandStrength: 0.5
  lightness: 0.913286377908662
  saturation: 0.5
  rhythmicContrast: 0.6992182373069227
purpose: []
